export const healthOptionsList = [
    { value: "alcohol-free", label: "Alcohol-Free", group: "health" },
    { value: "celery-free", label: "Celery-Free", group: "health" },
    { value: "crustacean-free", label: "Crustacean-Free", group: "health" },
    { value: "dairy-free", label: "Dairy-Free", group: "health" },
    { value: "egg-free", label: "Egg-Free", group: "health" },
    { value: "fish-free", label: "Fish-Free", group: "health" },
    { value: "fodmap-free", label: "FODMAP-Free", group: "health" },
    { value: "gluten-free", label: "Gluten-Free", group: "health" },
    { value: "keto-friendly", label: "Keto-Friendly", group: "health" },
    { value: "kidney-friendly", label: "Kidney-Friendly", group: "health" },
    { value: "kosher", label: "Kosher", group: "health" },
    { value: "low-potassium", label: "Low Potassium", group: "health" },
    { value: "lupine-free", label: "Lupine-Free", group: "health" },
    { value: "mustard-free", label: "Mustard-Free", group: "health" },
    { value: "no-oil-added", label: "No Oil Added", group: "health" },
    { value: "low-sugar", label: "Low Sugar", group: "health" },
    { value: "paleo", label: "Paleo", group: "health" },
    { value: "peanut-free", label: "Peanut-Free", group: "health" },
    { value: "pecatarian", label: "Pescatarian", group: "health" },
    { value: "pork-free", label: "Pork-Free", group: "health" },
    { value: "red-meat-free", label: "Red Meat-Free", group: "health" },
    { value: "sesame-free", label: "Sesame-Free", group: "health" },
    { value: "shellfish-free", label: "Shellfish-Free", group: "health" },
    { value: "soy-free", label: "Soy-Free", group: "health" },
    { value: "sugar-conscious", label: "Sugar-Conscious", group: "health" },
    { value: "tree-nut-free", label: "Tree Nut-Free", group: "health" },
    { value: "vegan", label: "Vegan", group: "health" },
    { value: "vegetarian", label: "Vegetarian", group: "health" },
    { value: "wheat-free", label: "Wheat-Free", group: "health" }
]

export const dietOptionsList = [
    { value: "balanced", label: "Balanced", group: "diet" },
    { value: "high-fiber", label: "High Fiber", group: "diet" },
    { value: "high-protein", label: "High Protein", group: "diet" },
    { value: "low-carb", label: "Low Carb", group: "diet" },
    { value: "low-fat", label: "Low Fat", group: "diet" },
    { value: "low-sodium", label: "Low Sodium", group: "diet" }
]
